FROM oven/bun:1

WORKDIR /usr/src/app

COPY ./packages ./packages

COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json

COPY ./package*.json ./package*.json

COPY turbo.json turbo.json

RUN bun install 
COPY ./apps/hub ./apps/hub

RUN bun db:generate




EXPOSE 8081

CMD [ "bun", "run", "hub" ]