FROM oven/bun:latest

WORKDIR /app

COPY ./apps/api ./apps/api
COPY ./packages/ ./packages
COPY package* .
COPY turbo.json .
COPY bun.lock .

RUN bun install

RUN bun run db:generate

EXPOSE 8080

CMD ["bun", "run", "api"]
