FROM oven/bun:1

WORKDIR /usr/src/app

COPY ./packages ./packages

COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json

COPY ./package*.json ./package*.json

COPY turbo.json turbo.json

RUN bun install 
COPY ./apps/api ./apps/api

RUN bun db:generate



EXPOSE 8080

CMD [ "bun", "run", "api" ]