FROM oven/bun:1
ARG DATABASE_URL

WORKDIR /usr/src/app

COPY ./packages ./packages

COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json

COPY ./package*.json ./package*.json
 
COPY turbo.json turbo.json


RUN bun install 

COPY ./apps/frontend ./apps/frontend

RUN echo "DATABASE_URL: ${DATABASE_URL}"

RUN DATABASE_URL=${DATABASE_URL}  bun db:generate
RUN DATABASE_URL=${DATABASE_URL}  bun run build


EXPOSE 3000

CMD [ "bun", "run", "frontend:prod" ]