export const JWT_PUBLIC_KEY =
  process.env.JWT_PUBLIC_KEY ||
  `-----BEGIN PUBLIC KEY-----
  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqhRzktxm2Z/vQlmwl4Md
  JpOoXSeT9RQWbE+XHRHp2UGaRVHhuZg5Tu2trXmn40R7BfZlWUuIgaKyqwYw1UkX
  pCYrpfX8vqwIELY33hm6Ssxt/nI6fXcyM6F/w0c/tCNxbSQj+dn5R0Oa3nY/zJc1
  RopATCkB2ZPT1obOERyEMNjnfrxcmIlK0tmOLsvkYXAjfDYNH29JrD/DGY7m0/Am
  VHWaJM/lIkL+Lwq++mmO2cWD3ya4WxUgKtIDUw9PX5WOUiDigC5OK/Px04glFIyS
  VG3I4BtsRt0s+G61DQjYZgrUHudJj7zVCGGHayMUrMCl37LWk1ply7RGrZlL78/M
  MQIDAQAB
-----END PUBLIC KEY-----
`;
