name: Docker push Frontend
on:
  push:
    branches: [development]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-actions@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB.TOKEN }}
      - name: Build and push frontend
        uses: docker/build-push-actions@v5
        with:
          context: .
          file: ./docker/Dockerfile.frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}:${{ github.sha}}
